# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/robin/Documents/kod/yane-0.6.6

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/robin/Documents/kod/yane-0.6.6

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robin/Documents/kod/yane-0.6.6/CMakeFiles /home/robin/Documents/kod/yane-0.6.6/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robin/Documents/kod/yane-0.6.6/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yane

# Build rule for target.
yane: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yane
.PHONY : yane

# fast build rule for target.
yane/fast:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/build
.PHONY : yane/fast

src/cartridge.o: src/cartridge.cpp.o
.PHONY : src/cartridge.o

# target to build an object file
src/cartridge.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/cartridge.cpp.o
.PHONY : src/cartridge.cpp.o

src/cartridge.i: src/cartridge.cpp.i
.PHONY : src/cartridge.i

# target to preprocess a source file
src/cartridge.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/cartridge.cpp.i
.PHONY : src/cartridge.cpp.i

src/cartridge.s: src/cartridge.cpp.s
.PHONY : src/cartridge.s

# target to generate assembly for a file
src/cartridge.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/cartridge.cpp.s
.PHONY : src/cartridge.cpp.s

src/cartridge_factory.o: src/cartridge_factory.cpp.o
.PHONY : src/cartridge_factory.o

# target to build an object file
src/cartridge_factory.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/cartridge_factory.cpp.o
.PHONY : src/cartridge_factory.cpp.o

src/cartridge_factory.i: src/cartridge_factory.cpp.i
.PHONY : src/cartridge_factory.i

# target to preprocess a source file
src/cartridge_factory.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/cartridge_factory.cpp.i
.PHONY : src/cartridge_factory.cpp.i

src/cartridge_factory.s: src/cartridge_factory.cpp.s
.PHONY : src/cartridge_factory.s

# target to generate assembly for a file
src/cartridge_factory.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/cartridge_factory.cpp.s
.PHONY : src/cartridge_factory.cpp.s

src/config.o: src/config.cpp.o
.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/controller.o: src/controller.cpp.o
.PHONY : src/controller.o

# target to build an object file
src/controller.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/controller.cpp.o
.PHONY : src/controller.cpp.o

src/controller.i: src/controller.cpp.i
.PHONY : src/controller.i

# target to preprocess a source file
src/controller.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/controller.cpp.i
.PHONY : src/controller.cpp.i

src/controller.s: src/controller.cpp.s
.PHONY : src/controller.s

# target to generate assembly for a file
src/controller.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/controller.cpp.s
.PHONY : src/controller.cpp.s

src/cpu.o: src/cpu.cpp.o
.PHONY : src/cpu.o

# target to build an object file
src/cpu.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/cpu.cpp.o
.PHONY : src/cpu.cpp.o

src/cpu.i: src/cpu.cpp.i
.PHONY : src/cpu.i

# target to preprocess a source file
src/cpu.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/cpu.cpp.i
.PHONY : src/cpu.cpp.i

src/cpu.s: src/cpu.cpp.s
.PHONY : src/cpu.s

# target to generate assembly for a file
src/cpu.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/cpu.cpp.s
.PHONY : src/cpu.cpp.s

src/ines.o: src/ines.cpp.o
.PHONY : src/ines.o

# target to build an object file
src/ines.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/ines.cpp.o
.PHONY : src/ines.cpp.o

src/ines.i: src/ines.cpp.i
.PHONY : src/ines.i

# target to preprocess a source file
src/ines.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/ines.cpp.i
.PHONY : src/ines.cpp.i

src/ines.s: src/ines.cpp.s
.PHONY : src/ines.s

# target to generate assembly for a file
src/ines.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/ines.cpp.s
.PHONY : src/ines.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mappers/mapper0.o: src/mappers/mapper0.cpp.o
.PHONY : src/mappers/mapper0.o

# target to build an object file
src/mappers/mapper0.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper0.cpp.o
.PHONY : src/mappers/mapper0.cpp.o

src/mappers/mapper0.i: src/mappers/mapper0.cpp.i
.PHONY : src/mappers/mapper0.i

# target to preprocess a source file
src/mappers/mapper0.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper0.cpp.i
.PHONY : src/mappers/mapper0.cpp.i

src/mappers/mapper0.s: src/mappers/mapper0.cpp.s
.PHONY : src/mappers/mapper0.s

# target to generate assembly for a file
src/mappers/mapper0.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper0.cpp.s
.PHONY : src/mappers/mapper0.cpp.s

src/mappers/mapper1.o: src/mappers/mapper1.cpp.o
.PHONY : src/mappers/mapper1.o

# target to build an object file
src/mappers/mapper1.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper1.cpp.o
.PHONY : src/mappers/mapper1.cpp.o

src/mappers/mapper1.i: src/mappers/mapper1.cpp.i
.PHONY : src/mappers/mapper1.i

# target to preprocess a source file
src/mappers/mapper1.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper1.cpp.i
.PHONY : src/mappers/mapper1.cpp.i

src/mappers/mapper1.s: src/mappers/mapper1.cpp.s
.PHONY : src/mappers/mapper1.s

# target to generate assembly for a file
src/mappers/mapper1.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper1.cpp.s
.PHONY : src/mappers/mapper1.cpp.s

src/mappers/mapper2.o: src/mappers/mapper2.cpp.o
.PHONY : src/mappers/mapper2.o

# target to build an object file
src/mappers/mapper2.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper2.cpp.o
.PHONY : src/mappers/mapper2.cpp.o

src/mappers/mapper2.i: src/mappers/mapper2.cpp.i
.PHONY : src/mappers/mapper2.i

# target to preprocess a source file
src/mappers/mapper2.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper2.cpp.i
.PHONY : src/mappers/mapper2.cpp.i

src/mappers/mapper2.s: src/mappers/mapper2.cpp.s
.PHONY : src/mappers/mapper2.s

# target to generate assembly for a file
src/mappers/mapper2.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper2.cpp.s
.PHONY : src/mappers/mapper2.cpp.s

src/mappers/mapper3.o: src/mappers/mapper3.cpp.o
.PHONY : src/mappers/mapper3.o

# target to build an object file
src/mappers/mapper3.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper3.cpp.o
.PHONY : src/mappers/mapper3.cpp.o

src/mappers/mapper3.i: src/mappers/mapper3.cpp.i
.PHONY : src/mappers/mapper3.i

# target to preprocess a source file
src/mappers/mapper3.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper3.cpp.i
.PHONY : src/mappers/mapper3.cpp.i

src/mappers/mapper3.s: src/mappers/mapper3.cpp.s
.PHONY : src/mappers/mapper3.s

# target to generate assembly for a file
src/mappers/mapper3.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper3.cpp.s
.PHONY : src/mappers/mapper3.cpp.s

src/mappers/mapper4.o: src/mappers/mapper4.cpp.o
.PHONY : src/mappers/mapper4.o

# target to build an object file
src/mappers/mapper4.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper4.cpp.o
.PHONY : src/mappers/mapper4.cpp.o

src/mappers/mapper4.i: src/mappers/mapper4.cpp.i
.PHONY : src/mappers/mapper4.i

# target to preprocess a source file
src/mappers/mapper4.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper4.cpp.i
.PHONY : src/mappers/mapper4.cpp.i

src/mappers/mapper4.s: src/mappers/mapper4.cpp.s
.PHONY : src/mappers/mapper4.s

# target to generate assembly for a file
src/mappers/mapper4.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper4.cpp.s
.PHONY : src/mappers/mapper4.cpp.s

src/mappers/mapper66.o: src/mappers/mapper66.cpp.o
.PHONY : src/mappers/mapper66.o

# target to build an object file
src/mappers/mapper66.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper66.cpp.o
.PHONY : src/mappers/mapper66.cpp.o

src/mappers/mapper66.i: src/mappers/mapper66.cpp.i
.PHONY : src/mappers/mapper66.i

# target to preprocess a source file
src/mappers/mapper66.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper66.cpp.i
.PHONY : src/mappers/mapper66.cpp.i

src/mappers/mapper66.s: src/mappers/mapper66.cpp.s
.PHONY : src/mappers/mapper66.s

# target to generate assembly for a file
src/mappers/mapper66.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper66.cpp.s
.PHONY : src/mappers/mapper66.cpp.s

src/mappers/mapper7.o: src/mappers/mapper7.cpp.o
.PHONY : src/mappers/mapper7.o

# target to build an object file
src/mappers/mapper7.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper7.cpp.o
.PHONY : src/mappers/mapper7.cpp.o

src/mappers/mapper7.i: src/mappers/mapper7.cpp.i
.PHONY : src/mappers/mapper7.i

# target to preprocess a source file
src/mappers/mapper7.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper7.cpp.i
.PHONY : src/mappers/mapper7.cpp.i

src/mappers/mapper7.s: src/mappers/mapper7.cpp.s
.PHONY : src/mappers/mapper7.s

# target to generate assembly for a file
src/mappers/mapper7.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper7.cpp.s
.PHONY : src/mappers/mapper7.cpp.s

src/mappers/mapper9.o: src/mappers/mapper9.cpp.o
.PHONY : src/mappers/mapper9.o

# target to build an object file
src/mappers/mapper9.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper9.cpp.o
.PHONY : src/mappers/mapper9.cpp.o

src/mappers/mapper9.i: src/mappers/mapper9.cpp.i
.PHONY : src/mappers/mapper9.i

# target to preprocess a source file
src/mappers/mapper9.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper9.cpp.i
.PHONY : src/mappers/mapper9.cpp.i

src/mappers/mapper9.s: src/mappers/mapper9.cpp.s
.PHONY : src/mappers/mapper9.s

# target to generate assembly for a file
src/mappers/mapper9.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/mappers/mapper9.cpp.s
.PHONY : src/mappers/mapper9.cpp.s

src/ppu.o: src/ppu.cpp.o
.PHONY : src/ppu.o

# target to build an object file
src/ppu.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/ppu.cpp.o
.PHONY : src/ppu.cpp.o

src/ppu.i: src/ppu.cpp.i
.PHONY : src/ppu.i

# target to preprocess a source file
src/ppu.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/ppu.cpp.i
.PHONY : src/ppu.cpp.i

src/ppu.s: src/ppu.cpp.s
.PHONY : src/ppu.s

# target to generate assembly for a file
src/ppu.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/ppu.cpp.s
.PHONY : src/ppu.cpp.s

src/renderer_factory.o: src/renderer_factory.cpp.o
.PHONY : src/renderer_factory.o

# target to build an object file
src/renderer_factory.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/renderer_factory.cpp.o
.PHONY : src/renderer_factory.cpp.o

src/renderer_factory.i: src/renderer_factory.cpp.i
.PHONY : src/renderer_factory.i

# target to preprocess a source file
src/renderer_factory.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/renderer_factory.cpp.i
.PHONY : src/renderer_factory.cpp.i

src/renderer_factory.s: src/renderer_factory.cpp.s
.PHONY : src/renderer_factory.s

# target to generate assembly for a file
src/renderer_factory.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/renderer_factory.cpp.s
.PHONY : src/renderer_factory.cpp.s

src/renderers/sdlrenderer.o: src/renderers/sdlrenderer.cpp.o
.PHONY : src/renderers/sdlrenderer.o

# target to build an object file
src/renderers/sdlrenderer.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/renderers/sdlrenderer.cpp.o
.PHONY : src/renderers/sdlrenderer.cpp.o

src/renderers/sdlrenderer.i: src/renderers/sdlrenderer.cpp.i
.PHONY : src/renderers/sdlrenderer.i

# target to preprocess a source file
src/renderers/sdlrenderer.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/renderers/sdlrenderer.cpp.i
.PHONY : src/renderers/sdlrenderer.cpp.i

src/renderers/sdlrenderer.s: src/renderers/sdlrenderer.cpp.s
.PHONY : src/renderers/sdlrenderer.s

# target to generate assembly for a file
src/renderers/sdlrenderer.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/renderers/sdlrenderer.cpp.s
.PHONY : src/renderers/sdlrenderer.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

src/yane.o: src/yane.cpp.o
.PHONY : src/yane.o

# target to build an object file
src/yane.cpp.o:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/yane.cpp.o
.PHONY : src/yane.cpp.o

src/yane.i: src/yane.cpp.i
.PHONY : src/yane.i

# target to preprocess a source file
src/yane.cpp.i:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/yane.cpp.i
.PHONY : src/yane.cpp.i

src/yane.s: src/yane.cpp.s
.PHONY : src/yane.s

# target to generate assembly for a file
src/yane.cpp.s:
	$(MAKE) -f CMakeFiles/yane.dir/build.make CMakeFiles/yane.dir/src/yane.cpp.s
.PHONY : src/yane.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... yane"
	@echo "... src/cartridge.o"
	@echo "... src/cartridge.i"
	@echo "... src/cartridge.s"
	@echo "... src/cartridge_factory.o"
	@echo "... src/cartridge_factory.i"
	@echo "... src/cartridge_factory.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/controller.o"
	@echo "... src/controller.i"
	@echo "... src/controller.s"
	@echo "... src/cpu.o"
	@echo "... src/cpu.i"
	@echo "... src/cpu.s"
	@echo "... src/ines.o"
	@echo "... src/ines.i"
	@echo "... src/ines.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mappers/mapper0.o"
	@echo "... src/mappers/mapper0.i"
	@echo "... src/mappers/mapper0.s"
	@echo "... src/mappers/mapper1.o"
	@echo "... src/mappers/mapper1.i"
	@echo "... src/mappers/mapper1.s"
	@echo "... src/mappers/mapper2.o"
	@echo "... src/mappers/mapper2.i"
	@echo "... src/mappers/mapper2.s"
	@echo "... src/mappers/mapper3.o"
	@echo "... src/mappers/mapper3.i"
	@echo "... src/mappers/mapper3.s"
	@echo "... src/mappers/mapper4.o"
	@echo "... src/mappers/mapper4.i"
	@echo "... src/mappers/mapper4.s"
	@echo "... src/mappers/mapper66.o"
	@echo "... src/mappers/mapper66.i"
	@echo "... src/mappers/mapper66.s"
	@echo "... src/mappers/mapper7.o"
	@echo "... src/mappers/mapper7.i"
	@echo "... src/mappers/mapper7.s"
	@echo "... src/mappers/mapper9.o"
	@echo "... src/mappers/mapper9.i"
	@echo "... src/mappers/mapper9.s"
	@echo "... src/ppu.o"
	@echo "... src/ppu.i"
	@echo "... src/ppu.s"
	@echo "... src/renderer_factory.o"
	@echo "... src/renderer_factory.i"
	@echo "... src/renderer_factory.s"
	@echo "... src/renderers/sdlrenderer.o"
	@echo "... src/renderers/sdlrenderer.i"
	@echo "... src/renderers/sdlrenderer.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/yane.o"
	@echo "... src/yane.i"
	@echo "... src/yane.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

